services:
  - type: web
    name: puente-tecnologico
    env: java
    plan: free
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/tecnologico-1.0.0.jar
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: PORT
        value: 10000
